version: "3.8"

services:

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - microservice-network
  eureka:
    build:
      context: ./eureka
      dockerfile: Dockerfile
    environment:
      - spring.zipkin.baseUrl = http://zipkin:9411/
    ports:
      - "8070:8070"
    networks:
      - microservice-network

  accounts:
    build:
        context: ./accounts
        dockerfile: Dockerfile
    image: service/accounts
    container_name: account-service
    environment:
      - eureka.client.serviceUrl.defaultZone = http://eureka:8070/eureka/
      - spring.zipkin.baseUrl = http://zipkin:9411/
    depends_on:
      - eureka
    ports:
      - "8080:8080"
    networks:
      - microservice-network

  loans:
    build:
        context: ./loans
        dockerfile: Dockerfile
    image: service/loan
    container_name: loan-service
    environment:
      - eureka.client.serviceUrl.defaultZone = http://eureka:8070/eureka/
      - spring.zipkin.baseUrl = http://zipkin:9411/
    depends_on:
      - eureka
    ports:
      - "8090:8090"
    networks:
      - microservice-network

  cards:
    build:
        context: ./cards
        dockerfile: Dockerfile
    image: service/card
    container_name: card-service
    environment:
      - eureka.client.serviceUrl.defaultZone = http://eureka:8070/eureka/
      - spring.zipkin.baseUrl = http://zipkin:9411/
    depends_on:
      - eureka
    ports:
      - "9000:9000"
    networks:
       - microservice-network

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    image: service/gateway
    container_name: gateway-service
    environment:
      - eureka.client.serviceUrl.defaultZone = http://eureka:8070/eureka/
      - spring.zipkin.baseUrl = http://zipkin:9411/
    ports:
      - "8072:8072"
    depends_on:
      - eureka
      - cards
      - loans
      - accounts

    networks:
      - microservice-network




networks:
  microservice-network: